name: binance_full
description: Unofficial Dart wrapper for Binance API (REST endpoints + Websockets).
version: 0.0.2
homepage: https://github.com/AmauryBuguet/binance_api
repository: https://github.com/AmauryBuguet/binance_api

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  convert: ^3.0.0
  http: ^0.13.0
  crypto: ^3.0.0
  web_socket_channel: ^2.0.0
  either_dart: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
